In [1]:
import gspread
import pandas as pd

In [2]:
# intialize google sheets config
# get all records needed in json format
#make sure to share the mail(found in the json file key) of your gcp service, share that with the google sheet

gc = gspread.service_account()
worksheet = gc.open("KOWOPE").sheet1

In [3]:
# get all records needed in json format
sheet = worksheet.get_all_records()
sheet[0]

{'Applicant_ID': 'Apcnt_1000032',
 'form_field1': 3236.0,
 'form_field2': 0.34875,
 'form_field3': 10.2006,
 'form_field4': 0.0,
 'form_field5': 0.0,
 'form_field6': 418564.0,
 'form_field7': 418564.0,
 'form_field8': 418564.0,
 'form_field9': 540710.0,
 'form_field10': 0.0,
 'form_field11': 1649749.0,
 'form_field12': 5446.0,
 'form_field13': 0.0,
 'form_field14': 48187375,
 'form_field15': 114686147.0,
 'form_field16': 0.0,
 'form_field17': 0.0,
 'form_field18': 0.0,
 'form_field19': 0.0,
 'form_field20': 0.0,
 'form_field21': '',
 'form_field22': '',
 'form_field23': '',
 'form_field24': '',
 'form_field25': 1086.0,
 'form_field26': 6204.0,
 'form_field27': 2676.0,
 'form_field28': 60.0,
 'form_field29': 14691.0,
 'form_field30': 9794.0,
 'form_field31': '',
 'form_field32': 238.0,
 'form_field33': 1.8334,
 'form_field34': 0.0,
 'form_field35': '',
 'form_field36': 22.0,
 'form_field37': 2.0,
 'form_field38': 14.0,
 'form_field39': 0.0,
 'form_field40': '',
 'form_field41': '',
 'form_field42': 0.8250000000000001,
 'form_field43': 1.01,
 'form_field44': 0.8,
 'form_field45': '',
 'form_field46': 0.0,
 'form_field47': 'charge',
 'form_field48': '',
 'form_field49': 0.0,
 'form_field50': 0.01122099590461203}

In [4]:
# create dataframe with the data
df = pd.DataFrame(sheet)

#create an empty sheet
sheet_empty = gc.create('Spreadsheet')

In [5]:
# check the first 5 rows
df.head()

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,...,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
0,Apcnt_1000032,3236.0,0.34875,10.2006,0.0,0.0,418564.0,418564.0,418564.0,540710.0,...,,0.825,1.01,0.8,,0.0,charge,,0.0,0.011221
1,Apcnt_1000048,3284.0,1.2736,2.9606,9.0198,0.0,0.0,9858816.0,49014.0,1510098.0,...,18.8415,0.507694,4.04,0.623248,1.0,0.0,lending,,0.504974,0.043525
2,Apcnt_1000052,,0.27505,0.06,0.0,0.0,,,,,...,,,0.0,,,,charge,,0.0,
3,Apcnt_1000076,3232.0,0.28505,2.8032,0.0,0.0,0.0,473802.0,473802.0,1724437.0,...,,0.916663,2.02,0.464224,,,charge,90.163742,0.788809,0.104029
4,Apcnt_1000080,3466.0,2.09545,0.8318,2.5182,0.0,19839.0,1150662.0,1150662.0,7860523.0,...,,0.234047,23.23,0.726688,0.0,0.0,lending,1303.587148,1.637733,0.163124

In [6]:
#  A new worksheet for new data.
worksheet2 = sheet_empty.add_worksheet(title="Spreadsheet", rows=100, cols=20)
print(worksheet2.get("A1"))

[]

In [7]:
df.columns

Index(['Applicant_ID', 'form_field1', 'form_field2', 'form_field3',
       'form_field4', 'form_field5', 'form_field6', 'form_field7',
       'form_field8', 'form_field9', 'form_field10', 'form_field11',
       'form_field12', 'form_field13', 'form_field14', 'form_field15',
       'form_field16', 'form_field17', 'form_field18', 'form_field19',
       'form_field20', 'form_field21', 'form_field22', 'form_field23',
       'form_field24', 'form_field25', 'form_field26', 'form_field27',
       'form_field28', 'form_field29', 'form_field30', 'form_field31',
       'form_field32', 'form_field33', 'form_field34', 'form_field35',
       'form_field36', 'form_field37', 'form_field38', 'form_field39',
       'form_field40', 'form_field41', 'form_field42', 'form_field43',
       'form_field44', 'form_field45', 'form_field46', 'form_field47',
       'form_field48', 'form_field49', 'form_field50'],
      dtype='object')